# Stock NeurIPS2018 Part 1. Data
This series is a reproduction of paper *the process in the paper Practical Deep Reinforcement Learning Approach for Stock Trading*. 

This is the first part of the NeurIPS2018 series, introducing how to use FinRL to fetch and process data that we need for ML/RL trading.

Other demos can be found at the repo of [FinRL-Tutorials]((https://github.com/AI4Finance-Foundation/FinRL-Tutorials)).

# Part 1. Install Packages

In [14]:
## install finrl library
#!pip install git+https://github.com/AI4Finance-Foundation/FinRL.git

In [6]:
import pandas as pd
import numpy as np
import datetime
import yfinance as yf

from finrl.meta.preprocessor.yahoodownloader import YahooDownloader
from finrl.meta.preprocessor.preprocessors import FeatureEngineer, data_split
from finrl import config_tickers
from finrl.config import INDICATORS


import itertools

# Part 2. Fetch data

[yfinance](https://github.com/ranaroussi/yfinance) is an open-source library that provides APIs fetching historical data form Yahoo Finance. In FinRL, we have a class called [YahooDownloader](https://github.com/AI4Finance-Foundation/FinRL/blob/master/finrl/meta/preprocessor/yahoodownloader.py) that use yfinance to fetch data from Yahoo Finance.

**OHLCV**: Data downloaded are in the form of OHLCV, corresponding to **open, high, low, close, volume,** respectively. OHLCV is important because they contain most of numerical information of a stock in time series. From OHLCV, traders can get further judgement and prediction like the momentum, people's interest, market trends, etc.

## Data for a single ticker

Here we provide two ways to fetch data with single ticker, let's take Apple Inc. (AAPL) as an example.

### Using yfinance

### Using FinRL

In [22]:
TRAIN_START_DATE = '2018-01-04'
TRAIN_END_DATE = '2024-01-01'
TRADE_START_DATE = '2024-01-01'
TRADE_END_DATE = '2024-10-22'

# 设置文件路径常量
MARKET_BREADTH_FILE_PATH = '/Users/pu17/Documents/stock/stock_price_prediction/data/processed/market_breadth_all_exchanges.csv'

In [23]:
import sys

# 添加环境路径
sys.path.append('/Users/pu17/Documents/stock/stock_price_prediction')
from feature.mysqlhandler import MySQLHandler
from config import OUTPUT_DIR
mysql_handler = MySQLHandler()
# 连接到数据库
mysql_handler.connect()
holiday_features= mysql_handler.fetch_table_as_dataframe('holiday_features_table')
market_breadth= mysql_handler.fetch_table_as_dataframe('market_breadth_table')
moneyflow_summary= mysql_handler.fetch_table_as_dataframe('moneyflow_summary_table')

/Users/pu17/Documents/stock/stock_price_prediction/feature/mysqlhandler.py:268: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, self.connection)

In [46]:
sz_df_finrl = YahooDownloader(
    start_date=TRAIN_START_DATE,
    end_date=TRADE_END_DATE,
    ticker_list=['603000.SS']
    # ['000001.SS', '399001.SZ', '603000.SS']
).fetch_data()
sz_df_finrl.tail()

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1644, 8)

,date,open,high,low,close,volume,tic,day
1639,2024-10-15,21.629999,22.299999,21.430000,21.500000,27427866,603000.SS,1
1640,2024-10-16,20.809999,21.799999,20.809999,21.420000,18923536,603000.SS,2
1641,2024-10-17,21.790001,22.000000,21.320000,21.340000,26361474,603000.SS,3
1642,2024-10-18,21.110001,22.440001,20.879999,21.830000,41045845,603000.SS,4
1643,2024-10-21,22.000000,22.750000,21.889999,22.309999,34505287,603000.SS,0

In FinRL's YahooDownloader, we modified the data frame to the form that convenient for further data processing process. We use adjusted close price instead of close price, and add a column representing the day of a week (0-4 corresponding to Monday-Friday).

In [47]:
sz_df_finrl.tail(5)

,date,open,high,low,close,volume,tic,day
1639,2024-10-15,21.629999,22.299999,21.430000,21.500000,27427866,603000.SS,1
1640,2024-10-16,20.809999,21.799999,20.809999,21.420000,18923536,603000.SS,2
1641,2024-10-17,21.790001,22.000000,21.320000,21.340000,26361474,603000.SS,3
1642,2024-10-18,21.110001,22.440001,20.879999,21.830000,41045845,603000.SS,4
1643,2024-10-21,22.000000,22.750000,21.889999,22.309999,34505287,603000.SS,0

# Part 3: Preprocess Data
We need to check for missing data and do feature engineering to convert the data point into a state.
* **Adding technical indicators**. In practical trading, various information needs to be taken into account, such as historical prices, current holding shares, technical indicators, etc. Here, we demonstrate two trend-following technical indicators: MACD and RSI.
* **Adding turbulence index**. Risk-aversion reflects whether an investor prefers to protect the capital. It also influences one's trading strategy when facing different market volatility level. To control the risk in a worst-case scenario, such as financial crisis of 2007–2008, FinRL employs the turbulence index that measures extreme fluctuation of asset price.

Hear let's take **MACD** as an example. Moving average convergence/divergence (MACD) is one of the most commonly used indicator showing bull and bear market. Its calculation is based on EMA (Exponential Moving Average indicator, measuring trend direction over a period of time.)

In [61]:
fe = FeatureEngineer(use_technical_indicator=True,
                     tech_indicator_list = INDICATORS,
                     use_vix=True,
                     use_turbulence=True,
                     user_defined_feature = False)

processed = fe.preprocess_data(sz_df_finrl)

[*********************100%***********************]  1 of 1 completed

Successfully added technical indicators
Shape of DataFrame:  (1709, 8)
Successfully added vix

Successfully added turbulence index

In [49]:
processed.shape

(1587, 18)

In [50]:
processed.head()

,date,open,high,low,close,volume,tic,day,macd,boll_ub,boll_lb,rsi_30,cci_30,dx_30,close_30_sma,close_60_sma,vix,turbulence
0,2018-01-04,11.14,11.25,11.05,10.536489,3999394,603000.SS,3,0.000000,10.609044,10.501838,100.000000,66.666667,100.000000,10.536489,10.536489,9.22,0.0
1,2018-01-05,11.20,11.29,11.12,10.574392,3660691,603000.SS,4,0.000850,10.609044,10.501838,100.000000,66.666667,100.000000,10.555441,10.555441,9.22,0.0
2,2018-01-08,11.18,11.20,10.97,10.545966,4343294,603000.SS,0,0.000202,10.591733,10.512832,56.311505,-93.423693,60.068796,10.552283,10.552283,9.52,0.0
3,2018-01-09,11.12,11.13,11.03,10.460689,3749106,603000.SS,1,-0.003177,10.626477,10.432291,23.902995,-92.901676,60.068796,10.529384,10.529384,10.08,0.0
4,2018-01-10,11.08,11.22,10.96,10.564916,5381492,603000.SS,2,-0.000798,10.626381,10.446600,55.953819,-22.812886,3.355005,10.536490,10.536490,9.82,0.0

In [62]:
# 检查 processed 数据框中 'date' 列的数据类型
print(processed['date'].dtype)

object

In [62]:
import sys
# 添加环境路径
sys.path.append('/Users/pu17/Documents/stock/stock_price_prediction')
from feature.mysqlhandler import MySQLHandler
from config import OUTPUT_DIR
mysql_handler = MySQLHandler()
# 连接到数据库
mysql_handler.connect()
# 获取数据并重命名列
holiday_features = mysql_handler.fetch_table_as_dataframe('holiday_features_table').rename(columns={'trade_date': 'date'})
market_breadth = mysql_handler.fetch_table_as_dataframe('market_breadth_table').rename(columns={'trade_date': 'date'})
moneyflow_summary = mysql_handler.fetch_table_as_dataframe('moneyflow_summary_table').rename(columns={'trade_date': 'date'})

/Users/pu17/Documents/stock/stock_price_prediction/feature/mysqlhandler.py:268: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, self.connection)

In [63]:
moneyflow_summary = moneyflow_summary.drop(columns=[
    'buy_sm_vol', 'buy_sm_amount', 'sell_sm_vol', 'sell_sm_amount',
    'buy_md_vol', 'buy_md_amount', 'sell_md_vol', 'sell_md_amount',
    'buy_lg_vol', 'buy_lg_amount', 'sell_lg_vol', 'sell_lg_amount',
    'buy_elg_vol', 'buy_elg_amount', 'sell_elg_vol', 'sell_elg_amount'
])

In [64]:
# 确保日期列是 datetime 类型
market_breadth['date'] = market_breadth['date'].astype(str)
moneyflow_summary['date'] = moneyflow_summary['date'].astype(str)
holiday_features['date'] = holiday_features['date'].astype(str)
# 检查转换是否成功
print(processed['date'].dtype)
print(market_breadth['date'].dtype)
print(moneyflow_summary['date'].dtype)
print(holiday_features['date'].dtype)

object
object
object
object

In [65]:
# 2. 根据 'tic' 选择对应的 'exchange' 进行匹配
def select_exchange(row):
    if row['tic'] == '399001.SZ':
        return 'SZSE'
    elif row['tic'] in ['000001.SS', '603000.SS']:
        return 'SSE'
    return None

# 为 df1 添加一个新列 'exchange'，根据 'tic' 来选择合适的交易所
processed['exchange'] = processed.apply(select_exchange, axis=1)
# holiday_features.drop(columns=['day'], inplace=True)

# 3. 左连接，基于 'date' 和 'exchange' 进行合并
processed = pd.merge(processed, market_breadth, how='left', on=['date', 'exchange'])

processed = pd.merge(processed, moneyflow_summary, how='left', on=['date', 'exchange'])
merged_df = pd.merge(processed, holiday_features, how='left', on='date')
# merged_df = pd.merge(processed, holiday_features, how='left', on='date')
# # 4. 删除 'trade_date' 和 'exchange' 列
merged_df.drop(columns=['exchange'], inplace=True)

# # 查看合并后的结果
# print(merged_df)
# processed=merged_df

In [69]:
processed.tail()

,date,open,high,low,close,volume,tic,day,macd,boll_ub,...,net_md_vol,net_md_amount,net_lg_vol,net_lg_amount,net_elg_vol,net_elg_amount,net_sm_pct,net_md_pct,net_lg_pct,net_elg_pct
1582,2024-10-14,21.450001,21.889999,20.820000,21.84,29646800,603000.SS,0,1.240124,24.821814,...,-2829716.0,-284797.48,-8225648.0,-402162.70,2506802.0,146534.01,0.006521,-0.003436,-0.004853,0.001768
1583,2024-10-15,21.629999,22.299999,21.430000,21.50,27427866,603000.SS,1,1.154609,24.955241,...,8673359.0,726582.65,-9183508.0,-705706.96,-11323407.0,-1162626.14,0.015512,0.009871,-0.009588,-0.015796
1584,2024-10-16,20.809999,21.799999,20.809999,21.42,18923536,603000.SS,2,1.068070,25.043839,...,-6446648.0,-131536.95,-4307814.0,-647130.71,4180473.0,-65286.06,0.013295,-0.002072,-0.010194,-0.001028
1585,2024-10-17,21.790001,22.000000,21.320000,21.34,26361474,603000.SS,3,0.981715,25.112608,...,6831321.0,460156.16,-7588656.0,-430155.50,-9073157.0,-586950.59,0.008316,0.006871,-0.006423,-0.008764
1586,2024-10-18,21.110001,22.440001,20.879999,21.83,41045845,603000.SS,4,0.941959,25.198196,...,-14590609.0,-1760748.26,-5456948.0,-556435.36,7017163.0,1648104.65,0.006982,-0.018375,-0.005807,0.017199

In [66]:
holiday_features.tail()
# holiday_features['date'] = pd.to_datetime(holiday_features['date'])
holiday_features.drop(columns=['day'], inplace=True)

In [57]:
merged_df = pd.merge(processed, holiday_features, how='left', on='date')

In [67]:
list_ticker = processed["tic"].unique().tolist()
list_date = list(pd.date_range(processed['date'].min(),processed['date'].max()).astype(str))
combination = list(itertools.product(list_date,list_ticker))

processed_full = pd.DataFrame(combination,columns=["date","tic"]).merge(processed,on=["date","tic"],how="left")
processed_full = processed_full[processed_full['date'].isin(processed['date'])]
processed_full = processed_full.sort_values(['date','tic'])

processed_full = processed_full.fillna(0)

In [68]:
processed_full.shape

(1587, 37)

# Part 4: Save the Data

### Split the data for training and trading

In [70]:
train = data_split(processed_full, TRAIN_START_DATE,TRAIN_END_DATE)
trade = data_split(processed_full, TRADE_START_DATE,TRADE_END_DATE)
print(len(train))
print(len(trade))

1404
183

### Save data to csv file

For Colab users, you can open the virtual directory in colab and manually download the files.

For users running on your local environment, the csv files should be at the same directory of this notebook.

In [71]:
train.to_csv('train_data.csv')
trade.to_csv('trade_data.csv')