# Stock NeurIPS2018 Part 1. Data
This series is a reproduction of paper *the process in the paper Practical Deep Reinforcement Learning Approach for Stock Trading*. 

This is the first part of the NeurIPS2018 series, introducing how to use FinRL to fetch and process data that we need for ML/RL trading.

Other demos can be found at the repo of [FinRL-Tutorials]((https://github.com/AI4Finance-Foundation/FinRL-Tutorials)).

# Part 1. Install Packages

In [14]:
## install finrl library
#!pip install git+https://github.com/AI4Finance-Foundation/FinRL.git

In [15]:
import pandas as pd
import numpy as np
import datetime
import yfinance as yf

from finrl.meta.preprocessor.yahoodownloader import YahooDownloader
from finrl.meta.preprocessor.preprocessors import FeatureEngineer, data_split
from finrl import config_tickers
from finrl.config import INDICATORS

import itertools

# Part 2. Fetch data

[yfinance](https://github.com/ranaroussi/yfinance) is an open-source library that provides APIs fetching historical data form Yahoo Finance. In FinRL, we have a class called [YahooDownloader](https://github.com/AI4Finance-Foundation/FinRL/blob/master/finrl/meta/preprocessor/yahoodownloader.py) that use yfinance to fetch data from Yahoo Finance.

**OHLCV**: Data downloaded are in the form of OHLCV, corresponding to **open, high, low, close, volume,** respectively. OHLCV is important because they contain most of numerical information of a stock in time series. From OHLCV, traders can get further judgement and prediction like the momentum, people's interest, market trends, etc.

## Data for a single ticker

Here we provide two ways to fetch data with single ticker, let's take Apple Inc. (AAPL) as an example.

### Using yfinance

### Using FinRL

In [16]:
TRAIN_START_DATE = '2019-01-04'
TRAIN_END_DATE = '2022-01-01'
TRADE_START_DATE = '2022-01-01'
TRADE_END_DATE = '2024-10-09'

# 设置文件路径常量
MARKET_BREADTH_FILE_PATH = '/Users/pu17/Documents/stock/stock_price_prediction/data/processed/market_breadth_all_exchanges.csv'

In [28]:
sz_df_finrl = YahooDownloader(
    start_date='2022-01-01',
    end_date='2024-10-15',
    ticker_list=['000001.SS', '399001.SZ', '603000.SS']
).fetch_data()
sz_df_finrl.tail()

[*********************100%***********************]  1 of 1 completed

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2010, 8)

,date,open,high,low,close,volume,tic,day
2005,2024-10-11,10366.570312,10378.459961,9935.820312,10060.740234,2635200,399001.SZ,4
2006,2024-10-11,22.600000,22.809999,21.110001,21.400000,39756535,603000.SS,4
2007,2024-10-14,3241.427979,3294.620117,3203.900879,3284.322998,631500,000001.SS,0
2008,2024-10-14,10118.379883,10361.690430,9966.990234,10327.400391,2744800,399001.SZ,0
2009,2024-10-14,21.450001,21.889999,20.820000,21.840000,29646800,603000.SS,0

In FinRL's YahooDownloader, we modified the data frame to the form that convenient for further data processing process. We use adjusted close price instead of close price, and add a column representing the day of a week (0-4 corresponding to Monday-Friday).

In [17]:
sz_df_finrl = YahooDownloader(
        start_date=TRAIN_START_DATE,
        end_date=TRADE_END_DATE,
        ticker_list=['000001.SS', '399001.SZ', '603000.SS']
    ).fetch_data()

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4176, 8)

In [18]:
sz_df_finrl.tail(5)

,date,open,high,low,close,volume,tic,day
4171,2024-09-30,9950.650391,10556.929688,9829.429688,10529.759766,4444500,399001.SZ,0
4172,2024-09-30,22.750000,23.629999,21.750000,23.510000,74490393,603000.SS,0
4173,2024-10-08,3674.405029,3674.405029,3372.187012,3489.774902,1313500,000001.SS,1
4174,2024-10-08,11864.110352,11864.110352,10834.500000,11495.099609,5537200,399001.SZ,1
4175,2024-10-08,25.860001,25.860001,22.370001,25.320000,92054588,603000.SS,1

# Part 3: Preprocess Data
We need to check for missing data and do feature engineering to convert the data point into a state.
* **Adding technical indicators**. In practical trading, various information needs to be taken into account, such as historical prices, current holding shares, technical indicators, etc. Here, we demonstrate two trend-following technical indicators: MACD and RSI.
* **Adding turbulence index**. Risk-aversion reflects whether an investor prefers to protect the capital. It also influences one's trading strategy when facing different market volatility level. To control the risk in a worst-case scenario, such as financial crisis of 2007–2008, FinRL employs the turbulence index that measures extreme fluctuation of asset price.

Hear let's take **MACD** as an example. Moving average convergence/divergence (MACD) is one of the most commonly used indicator showing bull and bear market. Its calculation is based on EMA (Exponential Moving Average indicator, measuring trend direction over a period of time.)

In [19]:
fe = FeatureEngineer(use_technical_indicator=True,
                     tech_indicator_list = INDICATORS,
                     use_vix=True,
                     use_turbulence=True,
                     user_defined_feature = False)

processed = fe.preprocess_data(sz_df_finrl)

[*********************100%***********************]  1 of 1 completed

Successfully added technical indicators
Shape of DataFrame:  (1449, 8)
Successfully added vix

Successfully added turbulence index

In [20]:
processed.head()

,date,open,high,low,close,volume,tic,day,macd,boll_ub,boll_lb,rsi_30,cci_30,dx_30,close_30_sma,close_60_sma,vix,turbulence
0,2019-01-04,2446.019043,2515.315918,2440.906982,2514.867920,168900,000001.SS,4,0.000000,2549.747172,2498.209860,100.0,66.666667,100.0,2514.867920,2514.867920,21.379999,0.0
1,2019-01-04,7022.120117,7284.839844,7011.330078,7284.839844,104000,399001.SZ,4,0.000000,2549.747172,2498.209860,100.0,66.666667,100.0,7284.839844,7284.839844,21.379999,0.0
2,2019-01-04,7.400000,7.800000,7.360000,7.401978,10490980,603000.SS,4,0.000000,2549.747172,2498.209860,100.0,66.666667,100.0,7.401978,7.401978,21.379999,0.0
3,2019-01-07,2528.698975,2536.978027,2515.508057,2533.089111,177300,000001.SS,0,0.408809,2549.747172,2498.209860,100.0,66.666667,100.0,2523.978516,2523.978516,21.400000,0.0
4,2019-01-07,7333.319824,7409.379883,7303.459961,7400.200195,105700,399001.SZ,0,2.588213,7505.664193,7179.375846,100.0,66.666667,100.0,7342.520020,7342.520020,21.400000,0.0

In [21]:
# 设置文件路径常量
MARKET_BREADTH_FILE_PATH = '/Users/pu17/Documents/stock/stock_price_prediction/data/processed/market_breadth_all_exchanges.csv'

market_breadth_data = pd.read_csv(MARKET_BREADTH_FILE_PATH)
market_breadth_data['date'] = pd.to_datetime(market_breadth_data['trade_date']).dt.strftime('%Y-%m-%d')

In [22]:
# 2. 根据 'tic' 选择对应的 'exchange' 进行匹配
def select_exchange(row):
    if row['tic'] == '399001.SZ':
        return 'SZSE'
    elif row['tic'] in ['000001.SS', '603000.SS']:
        return 'SSE'
    return None

# 为 df1 添加一个新列 'exchange'，根据 'tic' 来选择合适的交易所
processed['exchange'] = processed.apply(select_exchange, axis=1)

# 3. 左连接，基于 'date' 和 'exchange' 进行合并
merged_df = pd.merge(processed, market_breadth_data, how='left', on=['date', 'exchange'])

# 4. 删除 'trade_date' 和 'exchange' 列
merged_df.drop(columns=['trade_date', 'exchange'], inplace=True)

# 查看合并后的结果
print(merged_df)
processed=merged_df

            date         open          high          low         close  \
0     2019-01-04  2446.019043   2515.315918  2440.906982   2514.867920
1     2019-01-04  7022.120117   7284.839844  7011.330078   7284.839844
2     2019-01-04     7.400000      7.800000     7.360000      7.401978
3     2019-01-07  2528.698975   2536.978027  2515.508057   2533.089111
4     2019-01-07  7333.319824   7409.379883  7303.459961   7400.200195
...          ...          ...           ...          ...           ...
4024  2024-09-27  9100.769531   9619.769531  9100.769531   9514.860352
4025  2024-09-27    20.559999     21.799999    20.500000     21.620001
4026  2024-09-30  3194.721924   3358.587891  3153.697021   3336.497070
4027  2024-09-30  9950.650391  10556.929688  9829.429688  10529.759766
4028  2024-09-30    22.750000     23.629999    21.750000     23.510000

        volume        tic  day        macd      boll_ub  ...      cci_30  \
0       168900  000001.SS    4    0.000000  2549.747172  ...   66.666667
1       104000  399001.SZ    4    0.000000  2549.747172  ...   66.666667
2     10490980  603000.SS    4    0.000000  2549.747172  ...   66.666667
3       177300  000001.SS    0    0.408809  2549.747172  ...   66.666667
4       105700  399001.SZ    0    2.588213  7505.664193  ...   66.666667
...        ...        ...  ...         ...          ...  ...         ...
4024   3344300  399001.SZ    4  128.981466  9004.587701  ...  455.258793
4025  29471635  603000.SS    4    0.470700    20.365220  ...  339.499606
4026   1102300  000001.SS    0   60.782888  3138.216140  ...  391.560146
4027   4444500  399001.SZ    0  281.265718  9634.781942  ...  505.270954
4028  74490393  603000.SS    0    0.794204    21.679816  ...  379.185456

           dx_30  close_30_sma  close_60_sma        vix  turbulence  up_count  \
0     100.000000   2514.867920   2514.867920  21.379999    0.000000     432.0
1     100.000000   7284.839844   7284.839844  21.379999    0.000000    1892.0
2     100.000000      7.401978      7.401978  21.379999    0.000000     432.0
3     100.000000   2523.978516   2523.978516  21.400000    0.000000     417.0
4     100.000000   7342.520020   7342.520020  21.400000    0.000000    1829.0
...          ...           ...           ...        ...         ...       ...
4024   65.303408   8258.475765   8439.290894  16.959999   39.079470       NaN
4025   58.108345     18.052333     18.632061  16.959999   39.079470    2187.0
4026   74.192028   2836.867847   2876.371952  16.730000   85.245846    2259.0
4027   76.651936   8330.463753   8470.223055  16.730000   85.245846       NaN
4028   68.402707     18.212667     18.697593  16.730000   85.245846    2259.0

      down_count  up_down_ratio  market_breadth
0           25.0        17.2800           407.0
1           88.0        21.5000          1804.0
2           25.0        17.2800           407.0
3           35.0        11.9143           382.0
4          138.0        13.2536          1691.0
...          ...            ...             ...
4024         NaN            NaN             NaN
4025        59.0        37.0678          2128.0
4026         2.0      1129.4994          2257.0
4027         NaN            NaN             NaN
4028         2.0      1129.4994          2257.0

[4029 rows x 22 columns]

In [23]:
list_ticker = processed["tic"].unique().tolist()
list_date = list(pd.date_range(processed['date'].min(),processed['date'].max()).astype(str))
combination = list(itertools.product(list_date,list_ticker))

processed_full = pd.DataFrame(combination,columns=["date","tic"]).merge(processed,on=["date","tic"],how="left")
processed_full = processed_full[processed_full['date'].isin(processed['date'])]
processed_full = processed_full.sort_values(['date','tic'])

processed_full = processed_full.fillna(0)

In [24]:
processed_full.head()

,date,tic,open,high,low,close,volume,day,macd,boll_ub,...,cci_30,dx_30,close_30_sma,close_60_sma,vix,turbulence,up_count,down_count,up_down_ratio,market_breadth
0,2019-01-04,000001.SS,2446.019043,2515.315918,2440.906982,2514.867920,168900.0,4.0,0.000000,2549.747172,...,66.666667,100.0,2514.867920,2514.867920,21.379999,0.0,432.0,25.0,17.2800,407.0
1,2019-01-04,399001.SZ,7022.120117,7284.839844,7011.330078,7284.839844,104000.0,4.0,0.000000,2549.747172,...,66.666667,100.0,7284.839844,7284.839844,21.379999,0.0,1892.0,88.0,21.5000,1804.0
2,2019-01-04,603000.SS,7.400000,7.800000,7.360000,7.401978,10490980.0,4.0,0.000000,2549.747172,...,66.666667,100.0,7.401978,7.401978,21.379999,0.0,432.0,25.0,17.2800,407.0
9,2019-01-07,000001.SS,2528.698975,2536.978027,2515.508057,2533.089111,177300.0,0.0,0.408809,2549.747172,...,66.666667,100.0,2523.978516,2523.978516,21.400000,0.0,417.0,35.0,11.9143,382.0
10,2019-01-07,399001.SZ,7333.319824,7409.379883,7303.459961,7400.200195,105700.0,0.0,2.588213,7505.664193,...,66.666667,100.0,7342.520020,7342.520020,21.400000,0.0,1829.0,138.0,13.2536,1691.0

# Part 4: Save the Data

### Split the data for training and trading

In [25]:
train = data_split(processed_full, TRAIN_START_DATE,TRAIN_END_DATE)
trade = data_split(processed_full, TRADE_START_DATE,TRADE_END_DATE)
print(len(train))
print(len(trade))

2109
1920

### Save data to csv file

For Colab users, you can open the virtual directory in colab and manually download the files.

For users running on your local environment, the csv files should be at the same directory of this notebook.

In [26]:
train.to_csv('train_data.csv')
trade.to_csv('trade_data.csv')